package com.bookmyfood.paymentservice.entity;

import jakarta.persistence.*;
import lombok.Data;

@Entity
@Table(name = "payment_details")
@Data
public class Payment {
    
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    
    @Column(name = "order_id", nullable = false)
    private String orderId;
    
    @Column(name = "payment_amount", nullable = false)
    private Double paymentAmount;
    
    @Column(name = "payment_status", nullable = false)
    private Integer paymentStatus; // 0: Pending, 1: Completed, 2: Failed
    
    @Column(name = "payment_method", nullable = false)
    private String paymentMethod; // CREDIT_CARD, DEBIT_CARD, UPI, NET_BANKING
    
    @Column(name = "transaction_id")
    private String transactionId;
    
    @Column(name = "payment_timestamp")
    private String paymentTimestamp;
    
    @Column(name = "user_id")
    private String userId;
    
    // Getters and Setters will be generated by Lombok @Data
}
